# Site
repository: c0510gy/c0510gy.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sanggeon Yun
title: Prospective PhD Student
email: ggj06281@kookmin.ac.kr
website: c0510gy.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username: c0510gy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sang-geon-yun
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: '@sanggeon'
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Blog
    icon: fa fa-blog
    url: https://c0510gy.github.io/blog/
  - title: resume/CV
    icon: far fa-file
    url: https://c0510gy.github.io/resume/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I'm a prospective Ph.D. student currently working at Bio-Inspired Architecture and Systems Lab ([BIASLab](http://moimani.weebly.com/)) of Computer Science department at University of California, Irvine with professor Mohsen Imani.

  I am interested in machine learning and hyperdimensional computing.

content:
  - title: Education # Title for the section
    layout: list2 # Type of content section (list/text)
    content:
      - layout: left
        title: University of California, Irvine
        caption: (Anticipated) Aug. 2023 ~
        sub_title: Ph.D. Student in Computer Science (Anticipated enrollment at Fall 2023)
        image: images/uci_emblem.png
        description: |
          Bio-Inspired Architecture and Systems Lab ([BIASLab](http://moimani.weebly.com/))

      - layout: left
        title: Kookmin University
        caption: Mar. 2019 ~ Feb. 2023
        sub_title: Bachelor of Computer Science
        image: images/kmu_emblem.png
        description: |
          GPA: 4.49 / 4.5, Major GPA: 4.5 / 4.5

  - title: Research Experience
    layout: list2
    content:
      - layout: left
        title: Bio-Inspired Architecture and Systems (BIASLab), University of California Irvine
        sub_title: Undergraduate Research Intern
        image: images/uci_emblem.png
        caption: Jan, 2022 - Present

      - layout: left
        title: Human-Computer Interaction Laboratory (HCIL), Seoul National University
        sub_title: Undergraduate Research Intern
        image: images/snu_emblem.png
        caption: Jun, 2022 - Oct, 2022

      - layout: left
        title: Natural Language Processing Laboratory, Kookmin University
        sub_title: Undergraduate Research Intern
        image: images/kmu_emblem.png
        caption: Dec, 2021 - Jun, 2022

      - layout: left
        title: Information Security Lab, Kookmin University
        sub_title: Undergraduate Research Intern
        image: images/kmu_emblem.png
        caption: 2019 - Jun, 2020

  - title: Work Experience
    layout: list2
    content:
      - layout: left
        title: RiderDash
        sub_title: Software Engineer
        image: images/riderdash_logo.png
        caption: Jun, 2020 - Aug, 2021

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
