# Site
repository: c0510gy/c0510gy.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sanggeon Yun
title: CS Ph.D. Student @ UC Irvine
email: sanggeoy@uci.edu # ggj06281@kookmin.ac.kr
website: c0510gy.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
googlescholar_username: Qw2sWuMAAAAJ
github_username: c0510gy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sang-geon-yun
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: '@sanggeon'
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Blog
    icon: fa fa-blog
    url: https://c0510gy.github.io/blog/
  - title: resume/CV
    icon: far fa-file
    url: https://c0510gy.github.io/resume/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile2.jpeg
about_content: | # this will include new lines to allow paragraphs
  LOVE to solve challenging problems!

  I'm conducting an advanced research study focused on addressing key limitations associated with neural network-based models. Specifically, my research aims to overcome challenges related to the lack of transparency, absence of commonsense reasoning, susceptibility to hardware noise, and excessive power consumption. To achieve this, I'm introducing HDC (Hyperdimensional Computing) as an innovative approach within the Bio-Inspired Architecture and Systems Lab ([BIASLab](http://moimani.weebly.com/)) as a Ph.D. student of the Computer Science department at the University of California, Irvine under Professor Mohsen Imani. Through this cutting-edge research, I'm hoping to contribute in a step towards revolutionizing the field and paving the way for enhanced and more efficient computational models.

  Also interested in competitive programming(solving problems using algorithms & data structure).

content:
  - title: Education # Title for the section
    layout: list2 # Type of content section (list/text)
    content:
      - layout: left
        title: University of California, Irvine
        caption: July. 2023 ~
        sub_title: Ph.D. Student in Computer Science
        image: images/uci_emblem.png
        description: |
          Bio-Inspired Architecture and Systems Lab ([BIASLab](http://moimani.weebly.com/))

          ICS Dean's Recruitment Fellowship

      - layout: left
        title: Kookmin University
        caption: Mar. 2019 ~ Feb. 2023
        sub_title: Bachelor of Computer Science
        image: images/kmu_emblem.png
        description: |
          GPA: 4.49 / 4.5, Major GPA: 4.5 / 4.5

          Graduate with the highest honor (1st / 145 in College of Computer Science, 수석졸업)
          
          Graduate with Achievement Award (대내외공로상)

          4 years full scholarship (Merit-based undergraduate scholarships, 특기자 4년 전액 장학금)

  - title: Research Experience
    layout: list2
    content:
      - layout: left
        title: Bio-Inspired Architecture and Systems (BIASLab), University of California Irvine
        sub_title: Graduate Student Researcher
        image: images/biaslab_icon.png
        caption: Jul, 2023 - Present

      - layout: left
        title: Bio-Inspired Architecture and Systems (BIASLab), University of California Irvine
        sub_title: Undergraduate Research Intern
        image: images/uci_emblem.png
        caption: Jan, 2022 - Jul, 2023

      - layout: left
        title: Human-Computer Interaction Laboratory (HCIL), Seoul National University
        sub_title: Undergraduate Research Intern
        image: images/snu_emblem.png
        caption: Jun, 2022 - Oct, 2022

      - layout: left
        title: Natural Language Processing Laboratory, Kookmin University
        sub_title: Undergraduate Research Intern
        image: images/kmu_emblem.png
        caption: Dec, 2021 - Jun, 2022

      - layout: left
        title: Information Security Lab, Kookmin University
        sub_title: Undergraduate Research Intern
        image: images/kmu_emblem.png
        caption: 2019 - Jun, 2020

  - title: Work Experience
    layout: list2
    content:
      - layout: left
        title: RiderDash
        sub_title: Software Engineer
        image: images/riderdash_logo.png
        caption: Jun, 2020 - Aug, 2021

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
